baseURL = 'https://fervaldezjr.github.io/blog/'
languageCode = 'es-es'
title = "ğŸ§‘ğŸ½â€ğŸ’» fervaldezjr's blog"
theme = 'slick'

[menu]

    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        pageref = "/posts"
        weight = 1

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        title = "All categories"
        pageref = "/categories"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        pageref = "/tags"
        weight = 3

    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About this site"
        pageref = "/about"
        weight = 4

    [[menu.footer]]
        name = "GitHub"
        title = "GitHub profile"
        url = "https://github.com/fervaldezjr"
        weight = 1

    [[menu.footer]]
        name = "Linkedin"
        title = "Fernando Valdez Linkedin page"
        url = "https://www.linkedin.com/in/fervaldezjr/?locale=es_ES"
        weight = 2