baseURL = 'https://fervaldezjr.github.io/fervaldezjrblog/'
languageCode = 'es-es'
title = "ðŸ§‘ðŸ½â€ðŸ’» fervaldezjr's blog"
theme = "hugo-theme-console"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

    [[params.navlinks]]
    name = "posts/"
    url = "posts/"

    [[params.navlinks]]
    name = "tags/"
    url = "tags/"

    [[params.navlinks]]
    name = "about/"
    url = "about/"