baseURL = 'https://fervaldezjr.github.io/blog/'
languageCode = 'es-es'
title = "ðŸ§‘ðŸ½â€ðŸ’» fervaldezjr's blog"
theme = "hugo-theme-console"

[taxonomies]
  tag = "tags"

[menu]

    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        pageref = "/posts"
        weight = 1

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        title = "All categories"
        pageref = "/categories"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        pageref = "/tags"
        weight = 3

    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About this site"
        pageref = "/about"
        weight = 4

    [[menu.footer]]
        name = "GitHub"
        title = "GitHub profile"
        url = "https://github.com/fervaldezjr"
        weight = 1

    [[menu.footer]]
        name = "Linkedin"
        title = "Fernando Valdez Linkedin page"
        url = "https://www.linkedin.com/in/fervaldezjr/?locale=es_ES"
        weight = 2

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

    [[params.navlinks]]
    name = "posts/"
    url = "posts/"

    [[params.navlinks]]
    name = "tags/"
    url = "tags/"

    [[params.navlinks]]
    name = "about/"
    url = "about/"